# Generated by Django 4.2.7 on 2023-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
